# encoding: utf-8

# This file is part of py-serializable
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Paul Horton. All Rights Reserved.

name: Release

on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:

env:
  PYTHON_SEMANTIC_RELEASE_VERSION: "7.33.2"
  PYTHON_VERSION_DEFAULT: "3.10"
  POETRY_VERSION: "1.1.12"

jobs:
  release:
    # https://github.community/t/how-do-i-specify-job-dependency-running-in-another-workflow/16482
    # limit this to being run on regular commits, not the commits that semantic-release will create
    if: github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'chore(release):')
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - name: Checkout
        # see https://github.com/actions/checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python Environment
        # see https://github.com/actions/setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION_DEFAULT }}
          architecture: 'x64'

      - name: Install and configure Poetry
        # See https://github.com/marketplace/actions/install-poetry-action
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install dependencies
        run: poetry install --no-root

      - name: View poetry version
        run: poetry --version

      - name: Install semantic-release
        run: pip install python-semantic-release=={{ env.PYTHON_SEMANTIC_RELEASE_VERSION }}

      - name: Perform Release
        run: semantic-release publish
        env:
          GH_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
          REPOSITORY_USERNAME: __token__
          REPOSITORY_PASSWORD: ${{ secrets.PYPI_TOKEN }}

#      - name: Python Semantic Release
#        # see https://python-semantic-release.readthedocs.io/en/latest/automatic-releases/github-actions.html
#        # see https://github.com/python-semantic-release/python-semantic-release
#        uses: python-semantic-release/python-semantic-release@v7.33.2
#        with:
#          github_token:        ${{ secrets.GH_RELEASE_TOKEN }}
#          repository_username: __token__
#          repository_password: ${{ secrets.PYPI_TOKEN }}
#          pypi_token:          ${{ secrets.PYPI_TOKEN }}
